#!/bin/bash

docker_checks() {

  #specific checks - check to see if we're in a docker container
  dockercontainer=$(
    grep -i docker /proc/self/cgroup 2>/dev/null
    find / -name "*dockerenv*" -exec ls -la {} \; 2>/dev/null
  )
  if [ "$dockercontainer" ]; then
    echo -e "\e[$orange[+] Looks like we're in a Docker container:\e[$default\n$dockercontainer"
    echo -e "\n"
  fi

  #specific checks - check to see if we're a docker host
  dockerhost=$(
    docker --version 2>/dev/null
    docker ps -a 2>/dev/null
  )
  if [ "$dockerhost" ]; then
    echo -e "\e[$orange[+] Looks like we're hosting Docker:\e[$default\n$dockerhost"
    echo -e "\n"
  fi

  #specific checks - are we a member of the docker group
  dockergrp=$(id | grep -i docker 2>/dev/null)
  if [ "$dockergrp" ]; then
    echo -e "\e[$orange[+] We're a member of the (docker) group - could possibly misuse these rights!\e[$default\n$dockergrp"
    echo -e "\n"
  fi

  #specific checks - are there any docker files present
  dockerfiles=$(find / -name Dockerfile -exec ls -l {} \; 2>/dev/null)
  if [ "$dockerfiles" ]; then
    echo -e "\e[$red[-] Anything juicy in the Dockerfile:\e[$default\n$dockerfiles"
    echo -e "\n"
  fi

  #specific checks - are there any docker files present
  dockeryml=$(find / -name docker-compose.yml -exec ls -l {} \; 2>/dev/null)
  if [ "$dockeryml" ]; then
    echo -e "\e[$red[-] Anything juicy in docker-compose.yml:\e[$default\n$dockeryml"
    echo -e "\n"
  fi
}
