#!/bin/bash

networking_info() {
  echo -e "\e[00;33m### NETWORKING  ##########################################\e[00m"

  #nic information
  nicinfo=$(/sbin/ifconfig -a 2>/dev/null)
  if [ "$nicinfo" ]; then
    echo -e "\e[00;31m[-] Network and IP info:\e[00m\n$nicinfo"
    echo -e "\n"
  fi

  #nic information (using ip)
  nicinfoip=$(/sbin/ip a 2>/dev/null)
  if [ ! "$nicinfo" ] && [ "$nicinfoip" ]; then
    echo -e "\e[00;31m[-] Network and IP info:\e[00m\n$nicinfoip"
    echo -e "\n"
  fi

  arpinfo=$(arp -a 2>/dev/null)
  if [ "$arpinfo" ]; then
    echo -e "\e[00;31m[-] ARP history:\e[00m\n$arpinfo"
    echo -e "\n"
  fi

  arpinfoip=$(ip n 2>/dev/null)
  if [ ! "$arpinfo" ] && [ "$arpinfoip" ]; then
    echo -e "\e[00;31m[-] ARP history:\e[00m\n$arpinfoip"
    echo -e "\n"
  fi

  #dns settings
  nsinfo=$(grep "nameserver" /etc/resolv.conf 2>/dev/null)
  if [ "$nsinfo" ]; then
    echo -e "\e[00;31m[-] Nameserver(s):\e[00m\n$nsinfo"
    echo -e "\n"
  fi

  nsinfosysd=$(systemd-resolve --status 2>/dev/null)
  if [ "$nsinfosysd" ]; then
    echo -e "\e[00;31m[-] Nameserver(s):\e[00m\n$nsinfosysd"
    echo -e "\n"
  fi

  #default route configuration
  defroute=$(route 2>/dev/null | grep default)
  if [ "$defroute" ]; then
    echo -e "\e[00;31m[-] Default route:\e[00m\n$defroute"
    echo -e "\n"
  fi

  #default route configuration
  defrouteip=$(ip r 2>/dev/null | grep default)
  if [ ! "$defroute" ] && [ "$defrouteip" ]; then
    echo -e "\e[00;31m[-] Default route:\e[00m\n$defrouteip"
    echo -e "\n"
  fi

  #listening TCP
  tcpservs=$(netstat -ntpl 2>/dev/null)
  if [ "$tcpservs" ]; then
    echo -e "\e[00;31m[-] Listening TCP:\e[00m\n$tcpservs"
    echo -e "\n"
  fi

  tcpservsip=$(ss -t -l -n 2>/dev/null)
  if [ ! "$tcpservs" ] && [ "$tcpservsip" ]; then
    echo -e "\e[00;31m[-] Listening TCP:\e[00m\n$tcpservsip"
    echo -e "\n"
  fi

  #listening UDP
  udpservs=$(netstat -nupl 2>/dev/null)
  if [ "$udpservs" ]; then
    echo -e "\e[00;31m[-] Listening UDP:\e[00m\n$udpservs"
    echo -e "\n"
  fi

  udpservsip=$(ss -u -l -n 2>/dev/null)
  if [ ! "$udpservs" ] && [ "$udpservsip" ]; then
    echo -e "\e[00;31m[-] Listening UDP:\e[00m\n$udpservsip"
    echo -e "\n"
  fi
}
