#!/bin/bash

services_info() {
  echo -e "\e[$orange### SERVICES #############################################\e[$default"

  #running processes
  psaux=$(ps aux 2>/dev/null)
  if [ "$psaux" ]; then
    echo -e "\e[$red[-] Running processes:\e[$default\n$psaux"
    echo -e "\n"
  fi

  #lookup process binary path and permissisons
  procperm=$(ps aux 2>/dev/null | awk '{print $11}' | xargs -r ls -la 2>/dev/null | awk '!x[$0]++' 2>/dev/null)
  if [ "$procperm" ]; then
    echo -e "\e[$red[-] Process binaries and associated permissions (from above list):\e[$default\n$procperm"
    echo -e "\n"
  fi

  if [ "$export" ] && [ "$procperm" ]; then
    procpermbase=$(ps aux 2>/dev/null | awk '{print $11}' | xargs -r ls 2>/dev/null | awk '!x[$0]++' 2>/dev/null)
    mkdir $format/ps-export/ 2>/dev/null
    for i in $procpermbase; do cp --parents $i $format/ps-export/; done 2>/dev/null
  fi

  #anything 'useful' in inetd.conf
  inetdread=$(cat /etc/inetd.conf 2>/dev/null)
  if [ "$inetdread" ]; then
    echo -e "\e[$red[-] Contents of /etc/inetd.conf:\e[$default\n$inetdread"
    echo -e "\n"
  fi

  if [ "$export" ] && [ "$inetdread" ]; then
    mkdir $format/etc-export/ 2>/dev/null
    cp /etc/inetd.conf $format/etc-export/inetd.conf 2>/dev/null
  fi

  #very 'rough' command to extract associated binaries from inetd.conf & show permisisons of each
  inetdbinperms=$(awk '{print $7}' /etc/inetd.conf 2>/dev/null | xargs -r ls -la 2>/dev/null)
  if [ "$inetdbinperms" ]; then
    echo -e "\e[$red[-] The related inetd binary permissions:\e[$default\n$inetdbinperms"
    echo -e "\n"
  fi

  xinetdread=$(cat /etc/xinetd.conf 2>/dev/null)
  if [ "$xinetdread" ]; then
    echo -e "\e[$red[-] Contents of /etc/xinetd.conf:\e[$default\n$xinetdread"
    echo -e "\n"
  fi

  if [ "$export" ] && [ "$xinetdread" ]; then
    mkdir $format/etc-export/ 2>/dev/null
    cp /etc/xinetd.conf $format/etc-export/xinetd.conf 2>/dev/null
  fi

  xinetdincd=$(grep "/etc/xinetd.d" /etc/xinetd.conf 2>/dev/null)
  if [ "$xinetdincd" ]; then
    echo -e "\e[$red[-] /etc/xinetd.d is included in /etc/xinetd.conf - associated binary permissions are listed below:\e[$default"
    ls -la /etc/xinetd.d 2>/dev/null
    echo -e "\n"
  fi

  #very 'rough' command to extract associated binaries from xinetd.conf & show permisisons of each
  xinetdbinperms=$(awk '{print $7}' /etc/xinetd.conf 2>/dev/null | xargs -r ls -la 2>/dev/null)
  if [ "$xinetdbinperms" ]; then
    echo -e "\e[$red[-] The related xinetd binary permissions:\e[$default\n$xinetdbinperms"
    echo -e "\n"
  fi

  initdread=$(ls -la /etc/init.d 2>/dev/null)
  if [ "$initdread" ]; then
    echo -e "\e[$red[-] /etc/init.d/ binary permissions:\e[$default\n$initdread"
    echo -e "\n"
  fi

  #init.d files NOT belonging to root!
  initdperms=$(find /etc/init.d/ \! -uid 0 -type f 2>/dev/null | xargs -r ls -la 2>/dev/null)
  if [ "$initdperms" ]; then
    echo -e "\e[$red[-] /etc/init.d/ files not belonging to root:\e[$default\n$initdperms"
    echo -e "\n"
  fi

  rcdread=$(ls -la /etc/rc.d/init.d 2>/dev/null)
  if [ "$rcdread" ]; then
    echo -e "\e[$red[-] /etc/rc.d/init.d binary permissions:\e[$default\n$rcdread"
    echo -e "\n"
  fi

  #init.d files NOT belonging to root!
  rcdperms=$(find /etc/rc.d/init.d \! -uid 0 -type f 2>/dev/null | xargs -r ls -la 2>/dev/null)
  if [ "$rcdperms" ]; then
    echo -e "\e[$red[-] /etc/rc.d/init.d files not belonging to root:\e[$default\n$rcdperms"
    echo -e "\n"
  fi

  usrrcdread=$(ls -la /usr/local/etc/rc.d 2>/dev/null)
  if [ "$usrrcdread" ]; then
    echo -e "\e[$red[-] /usr/local/etc/rc.d binary permissions:\e[$default\n$usrrcdread"
    echo -e "\n"
  fi

  #rc.d files NOT belonging to root!
  usrrcdperms=$(find /usr/local/etc/rc.d \! -uid 0 -type f 2>/dev/null | xargs -r ls -la 2>/dev/null)
  if [ "$usrrcdperms" ]; then
    echo -e "\e[$red[-] /usr/local/etc/rc.d files not belonging to root:\e[$default\n$usrrcdperms"
    echo -e "\n"
  fi

  initread=$(ls -la /etc/init/ 2>/dev/null)
  if [ "$initread" ]; then
    echo -e "\e[$red[-] /etc/init/ config file permissions:\e[$default\n$initread"
    echo -e "\n"
  fi

  # upstart scripts not belonging to root
  initperms=$(find /etc/init \! -uid 0 -type f 2>/dev/null | xargs -r ls -la 2>/dev/null)
  if [ "$initperms" ]; then
    echo -e "\e[$red[-] /etc/init/ config files not belonging to root:\e[$default\n$initperms"
    echo -e "\n"
  fi

  systemdread=$(ls -lthR /lib/systemd/ 2>/dev/null)
  if [ "$systemdread" ]; then
    echo -e "\e[$red[-] /lib/systemd/* config file permissions:\e[$default\n$systemdread"
    echo -e "\n"
  fi

  # systemd files not belonging to root
  systemdperms=$(find /lib/systemd/ \! -uid 0 -type f 2>/dev/null | xargs -r ls -la 2>/dev/null)
  if [ "$systemdperms" ]; then
    echo -e "\e[$orange[+] /lib/systemd/* config files not belonging to root:\e[$default\n$systemdperms"
    echo -e "\n"
  fi
}
