#!/bin/bash

system_info() {
  echo -e "\e[$orange### SYSTEM ##############################################\e[$default"

  #basic kernel info
  unameinfo=$(uname -a 2>/dev/null)
  if [ "$unameinfo" ]; then
    echo -e "\e[$red[-] Kernel information:\e[$default"
    echo "$unameinfo"
    echo ""
  fi

  procver=$(cat /proc/version 2>/dev/null)
  if [ "$procver" ]; then
    echo -e "\e[$red[-] Kernel information (continued):\e[$default"
    echo "$procver"
    echo ""
  fi

  #search all *-release files for version info
  release=$(cat /etc/*-release 2>/dev/null)
  if [ "$release" ]; then
    echo -e "\e[$red[-] Specific release information:\e[$default"
    echo "$release"
    echo ""
  fi

  #target hostname info
  hostnamed=$(hostname 2>/dev/null)
  if [ "$hostnamed" ]; then
    echo -e "\e[$red[-] Hostname:\e[$default"
    echo "$hostnamed"
    echo ""
  fi
}
