#!/bin/bash

user_info() {
  echo -e "\e[00;33m### USER/GROUP ##########################################\e[00m"

  #current user details
  currusr=$(id 2>/dev/null)
  if [ "$currusr" ]; then
    echo -e "\e[00;31m[-] Current user/group info:\e[00m\n$currusr"
    echo -e "\n"
  fi

  #last logged on user information
  lastlogedonusrs=$(lastlog 2>/dev/null | grep -v "Never" 2>/dev/null)
  if [ "$lastlogedonusrs" ]; then
    echo -e "\e[00;31m[-] Users that have previously logged onto the system:\e[00m\n$lastlogedonusrs"
    echo -e "\n"
  fi

  #who else is logged on
  loggedonusrs=$(w 2>/dev/null)
  if [ "$loggedonusrs" ]; then
    echo -e "\e[00;31m[-] Who else is logged on:\e[00m\n$loggedonusrs"
    echo -e "\n"
  fi

  #lists all id's and respective group(s)
  grpinfo=$(for i in $(cut -d":" -f1 /etc/passwd 2>/dev/null); do echo -e "$i : $(id $i)"; done 2>/dev/null)
  if [ "$grpinfo" ]; then
    echo -e "\e[00;31m[-] Group memberships:\e[00m\n$grpinfo"
    echo -e "\n"
  fi

  #added by phackt - look for adm group (thanks patrick)
  adm_users=$(echo -e "$grpinfo" | grep "(adm)")
  if [[ ! -z $adm_users ]]; then
    echo -e "\e[00;31m[-] It looks like we have some admin users:\e[00m\n$adm_users"
    echo -e "\n"
  fi

  #checks to see if any hashes are stored in /etc/passwd (depreciated  *nix storage method)
  hashesinpasswd=$(grep -v '^[^:]*:[x]' /etc/passwd 2>/dev/null)
  if [ "$hashesinpasswd" ]; then
    echo -e "\e[00;33m[+] It looks like we have password hashes in /etc/passwd!\e[00m\n$hashesinpasswd"
    echo -e "\n"
  fi

  #contents of /etc/passwd
  readpasswd=$(cat /etc/passwd 2>/dev/null)
  if [ "$readpasswd" ]; then
    echo -e "\e[00;31m[-] Contents of /etc/passwd:\e[00m\n$readpasswd"
    echo -e "\n"
  fi

  if [ "$export" ] && [ "$readpasswd" ]; then
    mkdir $format/etc-export/ 2>/dev/null
    cp /etc/passwd $format/etc-export/passwd 2>/dev/null
  fi

  #checks to see if the shadow file can be read
  readshadow=$(cat /etc/shadow 2>/dev/null)
  if [ "$readshadow" ]; then
    echo -e "\e[00;33m[+] We can read the shadow file!\e[00m\n$readshadow"
    echo -e "\n"
  fi

  if [ "$export" ] && [ "$readshadow" ]; then
    mkdir $format/etc-export/ 2>/dev/null
    cp /etc/shadow $format/etc-export/shadow 2>/dev/null
  fi

  #checks to see if /etc/master.passwd can be read - BSD 'shadow' variant
  readmasterpasswd=$(cat /etc/master.passwd 2>/dev/null)
  if [ "$readmasterpasswd" ]; then
    echo -e "\e[00;33m[+] We can read the master.passwd file!\e[00m\n$readmasterpasswd"
    echo -e "\n"
  fi

  if [ "$export" ] && [ "$readmasterpasswd" ]; then
    mkdir $format/etc-export/ 2>/dev/null
    cp /etc/master.passwd $format/etc-export/master.passwd 2>/dev/null
  fi

  #all root accounts (uid 0)
  superman=$(grep -v -E "^#" /etc/passwd 2>/dev/null | awk -F: '$3 == 0 { print $1}' 2>/dev/null)
  if [ "$superman" ]; then
    echo -e "\e[00;31m[-] Super user account(s):\e[00m\n$superman"
    echo -e "\n"
  fi

  #pull out vital sudoers info
  sudoers=$(grep -v -e '^$' /etc/sudoers 2>/dev/null | grep -v "#" 2>/dev/null)
  if [ "$sudoers" ]; then
    echo -e "\e[00;31m[-] Sudoers configuration (condensed):\e[00m$sudoers"
    echo -e "\n"
  fi

  if [ "$export" ] && [ "$sudoers" ]; then
    mkdir $format/etc-export/ 2>/dev/null
    cp /etc/sudoers $format/etc-export/sudoers 2>/dev/null
  fi

  #can we sudo without supplying a password
  sudoperms=$(echo '' | sudo -S -l -k 2>/dev/null)
  if [ "$sudoperms" ]; then
    echo -e "\e[00;33m[+] We can sudo without supplying a password!\e[00m\n$sudoperms"
    echo -e "\n"
  fi

  #check sudo perms - authenticated
  if [ "$sudopass" ]; then
    if [ "$sudoperms" ]; then
      :
    else
      sudoauth=$(echo $user_password | sudo -S -l -k 2>/dev/null)
      if [ "$sudoauth" ]; then
        echo -e "\e[00;33m[+] We can sudo when supplying a password!\e[00m\n$sudoauth"
        echo -e "\n"
      fi
    fi
  fi

  ##known 'good' breakout binaries (cleaned to parse /etc/sudoers for comma separated values) - authenticated
  if [ "$sudopass" ]; then
    if [ "$sudoperms" ]; then
      :
    else
      sudopermscheck=$(echo $user_password | sudo -S -l -k 2>/dev/null | xargs -n 1 2>/dev/null | sed 's/,*$//g' 2>/dev/null | grep -w $binarylist 2>/dev/null)
      if [ "$sudopermscheck" ]; then
        echo -e "\e[00;33m[-] Possible sudo pwnage!\e[00m\n$sudopermscheck"
        echo -e "\n"
      fi
    fi
  fi

  #known 'good' breakout binaries (cleaned to parse /etc/sudoers for comma separated values)
  sudopwnage=$(echo '' | sudo -S -l -k 2>/dev/null | xargs -n 1 2>/dev/null | sed 's/,*$//g' 2>/dev/null | grep -w $binarylist 2>/dev/null)
  if [ "$sudopwnage" ]; then
    echo -e "\e[00;33m[+] Possible sudo pwnage!\e[00m\n$sudopwnage"
    echo -e "\n"
  fi

  #who has sudoed in the past
  whohasbeensudo=$(find /home -name .sudo_as_admin_successful 2>/dev/null)
  if [ "$whohasbeensudo" ]; then
    echo -e "\e[00;31m[-] Accounts that have recently used sudo:\e[00m\n$whohasbeensudo"
    echo -e "\n"
  fi

  #checks to see if roots home directory is accessible
  rthmdir=$(ls -ahl /root/ 2>/dev/null)
  if [ "$rthmdir" ]; then
    echo -e "\e[00;33m[+] We can read root's home directory!\e[00m\n$rthmdir"
    echo -e "\n"
  fi

  #displays /home directory permissions - check if any are lax
  homedirperms=$(ls -ahl /home/ 2>/dev/null)
  if [ "$homedirperms" ]; then
    echo -e "\e[00;31m[-] Are permissions on /home directories lax:\e[00m\n$homedirperms"
    echo -e "\n"
  fi

  #looks for files we can write to that don't belong to us
  if [ "$thorough" = "1" ]; then
    grfilesall=$(find / -writable ! -user $(whoami) -type f ! -path "/proc/*" ! -path "/sys/*" -exec ls -al {} \; 2>/dev/null)
    if [ "$grfilesall" ]; then
      echo -e "\e[00;31m[-] Files not owned by user but writable by group:\e[00m\n$grfilesall"
      echo -e "\n"
    fi
  fi

  #looks for files that belong to us
  if [ "$thorough" = "1" ]; then
    ourfilesall=$(find / -user $(whoami) -type f ! -path "/proc/*" ! -path "/sys/*" -exec ls -al {} \; 2>/dev/null)
    if [ "$ourfilesall" ]; then
      echo -e "\e[00;31m[-] Files owned by our user:\e[00m\n$ourfilesall"
      echo -e "\n"
    fi
  fi

  #looks for hidden files
  if [ "$thorough" = "1" ]; then
    hiddenfiles=$(find / -name ".*" -type f ! -path "/proc/*" ! -path "/sys/*" -exec ls -al {} \; 2>/dev/null)
    if [ "$hiddenfiles" ]; then
      echo -e "\e[00;31m[-] Hidden files:\e[00m\n$hiddenfiles"
      echo -e "\n"
    fi
  fi

  #looks for world-reabable files within /home - depending on number of /home dirs & files, this can take some time so is only 'activated' with thorough scanning switch
  if [ "$thorough" = "1" ]; then
    wrfileshm=$(find /home/ -perm -4 -type f -exec ls -al {} \; 2>/dev/null)
    if [ "$wrfileshm" ]; then
      echo -e "\e[00;31m[-] World-readable files within /home:\e[00m\n$wrfileshm"
      echo -e "\n"
    fi
  fi

  if [ "$thorough" = "1" ]; then
    if [ "$export" ] && [ "$wrfileshm" ]; then
      mkdir $format/wr-files/ 2>/dev/null
      for i in $wrfileshm; do cp --parents $i $format/wr-files/; done 2>/dev/null
    fi
  fi

  #lists current user's home directory contents
  if [ "$thorough" = "1" ]; then
    homedircontents=$(ls -ahl ~ 2>/dev/null)
    if [ "$homedircontents" ]; then
      echo -e "\e[00;31m[-] Home directory contents:\e[00m\n$homedircontents"
      echo -e "\n"
    fi
  fi

  #checks for if various ssh files are accessible - this can take some time so is only 'activated' with thorough scanning switch
  if [ "$thorough" = "1" ]; then
    sshfiles=$(find / \( -name "id_dsa*" -o -name "id_rsa*" -o -name "known_hosts" -o -name "authorized_hosts" -o -name "authorized_keys" \) -exec ls -la {} \; 2>/dev/null)
    if [ "$sshfiles" ]; then
      echo -e "\e[00;31m[-] SSH keys/host information found in the following locations:\e[00m\n$sshfiles"
      echo -e "\n"
    fi
  fi

  if [ "$thorough" = "1" ]; then
    if [ "$export" ] && [ "$sshfiles" ]; then
      mkdir $format/ssh-files/ 2>/dev/null
      for i in $sshfiles; do cp --parents $i $format/ssh-files/; done 2>/dev/null
    fi
  fi

  #is root permitted to login via ssh
  sshrootlogin=$(grep "PermitRootLogin " /etc/ssh/sshd_config 2>/dev/null | grep -v "#" | awk '{print  $2}')
  if [ "$sshrootlogin" = "yes" ]; then
    echo -e "\e[00;31m[-] Root is allowed to login via SSH:\e[00m"
    grep "PermitRootLogin " /etc/ssh/sshd_config 2>/dev/null | grep -v "#"
    echo -e "\n"
  fi
}
